name: Feature request
description: Suggest an improvement
title: "[Feature] "
body:
  - type: textarea
    attributes:
      label: Problem / use case
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
